---
apiVersion: v1
kind: Deployment
metadata:
  name: Backend-flask-k8s
spec:
  replicas: 1

  selectors:
    matchLabels:
      app: flask-backend

  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-con
          image: flask-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

      env:
        - name: REDIS_HOST
          value: "db-service"
        - name: REDIS_PORT
          value: "6379"
---
