---
apiVersion: v1
kind: Deployment
metadata:
  name: redis-flask-k8s
spec:
  replicas: 1

  selectors:
    matchLabels:
      app: flask-redis

  template:
    metadata:
      labels:
        app: flask-redis
    spec:
      containers:
        - name: redis-con
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
---
